#code written by Ztirom45
#LICENCE: GPL4

all:
	pio run -t upload
	pio device monitor -b 115200

build:
	pio run
monitor:
	pio device monitor -b 115200
setup_lsp:
	#create compile_commands with:
	pio run -t compiledb
